### ISSUE TITLE
전역 CSS 설정 변경

### ISSUE THREAD

**Issue by zellytozelly** [memory-makers/rolling-pager-client#13]
### ISSUE
- type : chore

### TODO
- 구현해야할 것
  - [x] 전체 기본 글꼴 변경
  - [x] tsx 파일 ts로 변경
  - [x] layout - onClick 주석

### 기타
- 논의 사항이나, 고려해야 할 점을 작성해주세요.
