### ISSUE TITLE
SVG 파일 React Component 설정

### ISSUE THREAD

**Issue by kyhyun** [memory-makers/rolling-pager-client#25]
### ISSUE
- type : chore

### TODO
- [ ] SVGR 관련 라이브러리 적용
  - [ ] vite-plugin-svgr 라이브러리 추가
  - [ ] vite.config.ts에 해당 라이브러리 적용 및 옵션 추가
- [ ] SVG 파일 타입스크립트 적용
  - [ ] custom.d.ts 추가 및 코드 작성
  - [ ] tsconfig.json 에 해당 파일 적용

### 기타
- 추후 필요한 옵션 추가 혹은 코드에 리팩토링이 필요한 경우 회의를 진행해서 이슈 생성하고 작업하면 되겠습니다.
