### ISSUE TITLE
전송완료/전송실패 페이지 레이아웃 구현

### ISSUE THREAD

**Issue by zellytozelly** [memory-makers/rolling-pager-client#27]
### ISSUE
- type : feat

### TODO
- [x] 구현해야할 것
  - [x] 전송 성공 조건  
  - [x] 전공 실패 조건 -> 제거하기로 결정
  - [x] 모달에 전공 실패 조건 추가
